package:
  name: giropops-senhas
  version: 1.0.0

archs:
- x86_64
- aarch64

environment:
  contents:
    repositories:
    - https://packages.wolfi.dev/os
    packages:
    - python3
    - py3-pip
    - ca-certificates-bundle
    - wolfi-base

pipeline:
- uses: fetch
  with:
    uri: "https://example.com/your-source-code.tar.gz"
    expected-sha256: "your-source-code-sha256"

- uses: apkbuild
  with:
    script: |
      cd /work
      pip install -r requirements.txt
      python setup.py install

- uses: package
  with:
    output: /work/packages
