package:
  name: giropops-senhas
  version: 0.1.0
  description: Um gerador de senhas.
  target-architecture:
  - x86_64
  copyright:
  - license: Apache-2.0
    paths:
    - "*"
  dependencies:
    runtime:
    - python3

environment:
  contents:
    repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
    - alpine-baselayout-data
    - ca-certificates-bundle
    - busybox
    - gcc
    - musl-dev
    - python3
    - python3-dev
    - py3-pip
    - py3-virtualenv

pipeline:
- name: Build Python application
  runs: |
    set -e
    python3 -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
    deactivate
- name: Package application
  runs: |
    mkdir -p /pkg/usr/local/bin
    cp -r * /pkg/usr/local/bin/
