apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: giropops-pod-monitor
  labels:
    app: giropops-senhas
  namespace: giropops-senhas
spec:
  namespaceSelector:
    matchNames:
    - giropops-senhas
  selector:
    matchLabels:
      app: giropops-senhas
  podMetricsEndpoints:
  - interval: 30s
    path: /metrics
    targetPort: 5000
