apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: giropops-senhas-prd-sm
spec:
  endpoints:
    - port: "http"
      path: "/metrics"
      interval: "30s"
      scrapeTimeout: "10s"
    - port: "http"
      path: "/health"
      interval: "30s"
      scrapeTimeout: "10s"
  namespaceSelector:
    matchNames:
      - giropops-senhas-prd
  selector:
    matchLabels:
      app: giropops-senhas-prd-giropops-senhas
