apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
spec:
  acme:
    email: contato@nataliagranato.xyz
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: api-token
            name: cloudflare-api-token-secret
          email: natalia.granato@jackexperts.com
      selector:
        dnsZones:
        - nataliagranato.xyz
        - '*.nataliagranato.xyz'
