name: Download Artifacts

on:
    push:
      branches:
        - 'main'

jobs:

  download:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Download dev packages
      uses: actions/download-artifact@v2
      with:
        name: packages-dev
        path: dev-packages
        
    - name: Download staging packages  
      uses: actions/download-artifact@v2
      with:
        name: packages-staging
        path: staging-packages
        
    - name: Download prod packages
      uses: actions/download-artifact@v2
      with:
        name: packages-prod
        path: prod-packages
