name: Build e Distribuição de Pacotes com Melange e APKO

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build e Distribuição de Pacotes
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    # Passo 1: Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # Passo 2: Configurar Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Passo 3: Instalar Melange
    - name: Install Melange
      run: |
        wget https://github.com/chainguard-dev/melange/releases/download/v0.11.2/melange_0.11.2_linux_386.tar.gz
        tar -xzf melange_0.11.2_linux_386.tar.gz
        sudo mv melange /usr/local/bin/
        melange version

    # Passo 4: Instalar APKO
    - name: Install APKO
      run: |
        wget https://github.com/chainguard-dev/apko/releases/download/v0.14.7/apko_0.14.7_linux_386.tar.gz
        tar -xzf apko_0.14.7_linux_386.tar.gz
        sudo mv apko /usr/local/bin/
        apko version

    # Passo 5: Gerar chaves com Melange
    - name: Generate keys with Melange
      run: |
        cd chainguard
        melange keygen

    # Passo 6: Construir pacotes com Melange
    - name: Build packages with Melange
      run: |
        cd chainguard
        melange build melange.yaml --runner docker --signing-key melange.rsa --arch amd64

    # Passo 7: Construir imagem de container com APKO
    - name: Build container image with APKO
      run: |
        cd chainguard
        apko build apko.yaml senhas senhas.tar -k melange.rsa.pub --arch amd64

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Load Docker image
      run: |
        docker load < senhas.tar
        docker images
    
    - name: Extrair metadados (tags, labels) para Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
          images: nataliagranato/senhas

    - name: Gerar nome único para a tag
      id: generate-tag
      run: |
            # Obtém os primeiros 5 dígitos do hash do commit e a data
            SHORT_HASH=$(git log -1 --pretty=format:%h | cut -c1-5)
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            echo "tag=${SHORT_HASH}-${TIMESTAMP}" >> $GITHUB_ENV
            echo "::set-output name=tag::${SHORT_HASH}-${TIMESTAMP}"   

    - name: Push Docker image
      run: |   
        docker tag senhas:latest-amd64 ${{ secrets.DOCKER_USERNAME }}/senhas:${{ steps.generate-tag.outputs.tag }}
        docker push ${{ secrets.DOCKER_USERNAME }}/senhas:${{ steps.generate-tag.outputs.tag }}



