name: Deploy Helm Chart

on:
  push:
    branches:
      - main  # Branch usada para deploys

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # Passo 2: Clonar o repositório com Helm Charts
    - name: Clone Helm Charts Repository
      env:
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git clone https://$GH_USERNAME:$GH_TOKEN@github.com/nataliagranato/giropops-senhas-charts.git
        cd giropops-senhas-charts

    # Passo 3: Instalar kubectl
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # Passo 4: Configurar a conexão com o cluster Kubernetes
    - name: Configure Kubernetes context
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "$KUBECONFIG" | base64 --decode > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig
        kubectl get nodes

    # Passo 5: Instalar Helm
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: 'latest'

    # Passo 6: Criar namespaces se não existirem
    - name: Create namespaces
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "$KUBECONFIG" | base64 --decode > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig
        kubectl create namespace giropops-senhas-prd || true
        kubectl create namespace giropops-senhas-dev || true
        kubectl create namespace giropops-senhas-stg || true

    # Passo 7: Instalar o Helm Chart em três ambientes diferentes
    - name: Deploy Helm Chart to Production
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        cd giropops-senhas-charts/charts/giropops-senhas
        echo "$KUBECONFIG" | base64 --decode > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig
        helm upgrade --install giropops-senhas ./ \
          --namespace giropops-senhas-prd \
          --values ./prd.yaml

    - name: Deploy Helm Chart to Development
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        cd giropops-senhas-charts/charts/giropops-senhas
        echo "$KUBECONFIG" | base64 --decode > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig
        helm upgrade --install giropops-senhas-dev ./ \
          --namespace giropops-senhas-dev \
          --values ./dev.yaml

    - name: Deploy Helm Chart to Staging
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        cd giropops-senhas-charts/charts/giropops-senhas
        echo "$KUBECONFIG" | base64 --decode > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig
        helm upgrade --install giropops-senhas-stg ./ \
          --namespace giropops-senhas-stg \
          --values ./stg.yaml
  