name: Build Docker Image
on:
  push:
    branches:
    - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@2b51285047da1547ffb1b2203d8be4c0af6b1f20

    - name: Log in to Docker Hub
      uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@75359341f62c2d990e0aa8543e545c74eec643ff
      with:
        images: nataliagranato/linuxtips-giropops-senhas

    - name: Build and push Docker image
      uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
      id: build-and-push
      with:
        context: ./giropops-senhas
        file: ./giropops-senhas/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@062f2592684a31eb3aa050cc61e7ca1451cecd3d
      with:
        image-ref: nataliagranato/linuxtips-giropops-senhas:1.0
        format: 'sarif'
        severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
