name: Build APKs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        environment: [prod] # dev, staging, prod
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Melange
      run: |
        wget https://github.com/chainguard-dev/melange/releases/download/v0.11.2/melange_0.11.2_linux_386.tar.gz
        tar -xzf melange_0.11.2_linux_386.tar.gz
        cd melange_0.11.2_linux_386
        sudo mv melange /usr/local/bin/
        melange version
        
    - name: Generate keys with Melange
      run: |
        cd chainguard
        melange keygen
        
    - name: Build packages with Melange
      run: |
        cd chainguard
        melange build melange-${{ matrix.environment }}.yaml --runner docker --signing-key melange.rsa --arch amd64
        
    - name: Publish packages
      uses: actions/upload-artifact@v2
      with:
        name: packages-${{ matrix.environment }}
        path: chainguard/packages/x86_64
